name: Linux File Creation Autograding

on:
  workflow_dispatch:

jobs:
  autograding:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Give Execute Permission
        run: chmod +x student.sh tests/test_create_files.sh

      - name: Run Student Program
        run: ./student.sh

      - name: Run Test Cases
        run: ./tests/test_create_files.sh
